version: "2"

services:
  node1: 
    container_name: flum_worker1
    build: ./worker
    image: flum_worker
    volumes:
      - ./worker:/usr/src/app
  node2: 
    container_name: flum_worker2
    build: ./worker
    image: flum_worker
    volumes:
      - ./worker:/usr/src/app

  node3: 
    container_name: flum_worker3
    build: ./worker
    image: flum_worker
    volumes:
      - ./worker:/usr/src/app
  
  node4: 
    container_name: flum_worker4
    build: ./worker
    image: flum_worker
    volumes:
      - ./worker:/usr/src/app

  mq:
    container_name: flum_mq
    image: rabbitmq:3
    ports:
      - 5672:5672
  mongo:
    container_name: flum_mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  

  